apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rentalservice
    version: "1.0"
  name: rentalservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rentalservice
  strategy: {}
  template:
    metadata:
      labels:
        app: rentalservice
    spec:
      containers:
        - name: rentalservice
          image: eudemonia01/rentalservice
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30  # Ajout pour éviter des arrêts brutaux

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: rentalservice
  name: rentalservice
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: rentalservice
  type: LoadBalancer

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: rentalservice-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rentalservice
spec:
  hosts:
    - "*"
  gateways:
    - rentalservice-gateway
  http:
    - match:
        - uri:
            prefix: "/rentalservice"
      route:
        - destination:
            host: rentalservice.default.svc.cluster.local
            port:
              number: 80
