name: CI

on:
  pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x ProgDistTassadit/gradlew

      - name: Build with Gradle
        working-directory: ProgDistTassadit
        run: |
          export SHELL=/bin/bash
          ./gradlew build

