name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build, Test, and Deploy

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configurer JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      # Étape 3 : Build Gradle et exécuter les tests
      - name: Build and Test with Gradle
        working-directory: .
        run: |
          ./gradlew clean build

      # Étape 4 : Construire l'image Docker
      - name: Build Docker Image
        run: |
          docker build -t programmation-distr-service:latest .

      # Étape 5 : Vérification des images Docker
      - name: List Docker Images
        run: |
          docker images

